# Generated by Django 4.2.7 on 2025-12-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['group', 'order', 'name'], 'verbose_name': 'Task Type', 'verbose_name_plural': 'Task Types'},
        ),
        migrations.AddField(
            model_name='tasktype',
            name='auto_complete',
            field=models.BooleanField(default=True, help_text='Auto-complete when done'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='category',
            field=models.CharField(blank=True, help_text='Category: grooming, sales, media, housekeeping, general', max_length=50),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='count_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='count_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='max_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='max_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Requires manager approval'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='requires_evidence',
            field=models.BooleanField(default=False, help_text='Requires photo/video evidence'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='rule_config',
            field=models.JSONField(blank=True, help_text='Additional rule configuration', null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='rule_type',
            field=models.CharField(blank=True, help_text='Type of rule to apply', max_length=50),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='time_limit_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='time_limit_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='view_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='view_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='points',
            field=models.IntegerField(default=0, help_text='Base points for this task'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price if applicable', max_digits=7, null=True),
        ),
    ]
