# Generated by Django 4.2.7 on 2025-12-18 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0002_alter_tasktype_options_tasktype_auto_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='task_proofs/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('requested_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('task_date', models.DateField(help_text='Date when task was completed')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='task_requests/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['group', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_tasks_i_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='photo_proof',
            field=models.TextField(blank=True, help_text='Comma-separated image paths'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('point_request', 'Point Request'), ('package_created', 'Package Created'), ('approval_needed', 'Approval Needed'), ('points_awarded', 'Points Awarded'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_point_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='date_completed',
            field=models.DateField(help_text='Date when the task was actually completed'),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='manager_notes',
            field=models.TextField(blank=True, help_text="Manager's notes on approval/rejection"),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='points_awarded',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual points awarded (may differ from requested)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='points_requested',
            field=models.DecimalField(decimal_places=2, help_text='Points requested for this task', max_digits=6),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='proof_photo',
            field=models.ImageField(blank=True, help_text='Photo proof of completed task', null=True, upload_to='point_requests/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='reason',
            field=models.CharField(choices=[('not_in_system', 'Task Not in System'), ('emergency', 'Emergency Task'), ('special_request', 'Special Customer Request'), ('additional_work', 'Additional Work Required'), ('other', 'Other')], default='not_in_system', max_length=50),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='reason_details',
            field=models.TextField(blank=True, help_text='Explain why this task deserves points'),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='request_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointrequest',
            name='task_type',
            field=models.ForeignKey(blank=True, help_text='Select task type from list, or describe in reason_details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.tasktype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='auto_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='requires_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='rule_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='task_manage_user_id_329478_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='task_manage_created_67e31e_idx'),
        ),
        migrations.AddIndex(
            model_name='pointrequest',
            index=models.Index(fields=['staff', 'approval_status'], name='task_manage_staff_i_258fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='pointrequest',
            index=models.Index(fields=['approval_status', '-created_at'], name='task_manage_approva_e002b3_idx'),
        ),
        migrations.AddIndex(
            model_name='pointrequest',
            index=models.Index(fields=['date_completed'], name='task_manage_date_co_b7fc36_idx'),
        ),
        migrations.AddField(
            model_name='taskrequestimage',
            name='task_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task_management.taskrequest'),
        ),
        migrations.AddField(
            model_name='taskrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrequest',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task_management.task'),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taskrequest',
            index=models.Index(fields=['staff', 'status'], name='task_manage_staff_i_83da67_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrequest',
            index=models.Index(fields=['status', '-requested_at'], name='task_manage_status_0f03b0_idx'),
        ),
    ]
