# Generated by Django 4.2.7 on 2025-12-19 03:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0003_taskimage_taskrequest_taskrequestimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(help_text='Date of this closing report')),
                ('branch', models.CharField(help_text='Branch this report is for', max_length=50)),
                ('grooming_count', models.IntegerField(default=0, help_text='a. Numbers of cat grooming today')),
                ('boarding_count', models.IntegerField(default=0, help_text='b. Numbers of boarded room today')),
                ('total_customers', models.IntegerField(default=0, help_text='c. Numbers of customers today')),
                ('payment_record_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='d. Total payment record (RM)', max_digits=10)),
                ('payment_receipt_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='e. Total payment receipt (RM)', max_digits=10)),
                ('payment_proof_photo', models.ImageField(help_text='Photo or screenshot of payment record', upload_to='closing_reports/%Y/%m/%d/')),
                ('compliance_all_paid_through_system', models.BooleanField(default=True, help_text='f.i Do all customers are registered and paid through system?')),
                ('compliance_free_services_today', models.BooleanField(default=False, help_text='f.ii Is there any service with no payment today?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average of payment record and receipt', max_digits=10)),
                ('submitted_by', models.ForeignKey(help_text='Manager who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_closing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Closing Report',
                'verbose_name_plural': 'Closing Reports',
                'ordering': ['-date', '-submitted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='taskrequestimage',
            name='task_request',
        ),
        migrations.DeleteModel(
            name='TaskRequest',
        ),
        migrations.DeleteModel(
            name='TaskRequestImage',
        ),
        migrations.AddIndex(
            model_name='closingreport',
            index=models.Index(fields=['date', 'branch'], name='task_manage_date_549202_idx'),
        ),
        migrations.AddIndex(
            model_name='closingreport',
            index=models.Index(fields=['branch', '-date'], name='task_manage_branch_558822_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='closingreport',
            unique_together={('date', 'branch')},
        ),
    ]
