# Generated by Django 4.2.7 on 2025-12-19 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0004_closingreport_remove_taskrequestimage_task_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('activate', 'Activated'), ('deactivate', 'Deactivated'), ('password_reset', 'Password Reset'), ('task_reassign', 'Tasks Reassigned')], max_length=20)),
                ('model_type', models.CharField(choices=[('tasktype', 'Task Type'), ('taskgroup', 'Task Group'), ('user', 'User/Staff'), ('task', 'Task')], max_length=20)),
                ('object_id', models.CharField(help_text='ID of affected object', max_length=100)),
                ('object_repr', models.CharField(help_text='String representation', max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='JSON of what changed (before/after)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_type', 'object_id'], name='task_manage_model_t_1d4cdd_idx'), models.Index(fields=['user', '-timestamp'], name='task_manage_user_id_dfa983_idx'), models.Index(fields=['-timestamp'], name='task_manage_timesta_88d772_idx')],
            },
        ),
    ]
