# Generated by Django 4.2.7 on 2025-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='branch',
            field=models.CharField(choices=[('hq', 'HQ'), ('damansara_perdana', 'Damansara Perdana'), ('wangsa_maju', 'Wangsa Maju'), ('shah_alam', 'Shah Alam'), ('bangi', 'Bangi'), ('cheng_melaka', 'Cheng, Melaka'), ('johor_bahru', 'Johor Bahru'), ('seremban', 'Seremban 2'), ('seri_kembangan', 'Seri Kembangan'), ('usj21', 'USJ 21'), ('ipoh', 'Ipoh')], default='seri_kembangan', help_text='Branch where this package will be serviced', max_length=50),
        ),
    ]
