# Generated by Django 4.2.7 on 2025-12-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_taskpackage_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_id',
            field=models.CharField(blank=True, editable=False, help_text='Format: CAT133001239 (CAT + 3random + 3count + 3random)', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cat_photos/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['cat_id'], name='task_manage_cat_id_16b7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['owner', 'name'], name='task_manage_owner_i_9b0311_idx'),
        ),
    ]
