# Generated by Django 4.2.7 on 2026-01-02 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0007_alter_cat_cat_id_alter_cat_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='arrival_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When manager confirmed customer arrival', null=True),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='arrival_status',
            field=models.CharField(choices=[('pending', 'Pending Arrival'), ('arrived', 'Customer Arrived'), ('no_show', 'Customer No-Show')], default='pending', help_text='Customer arrival confirmation status', max_length=20),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='booking_type',
            field=models.CharField(choices=[('type_a', 'Type A - Got Proof (Award Now)'), ('type_c', 'Type C - No Proof (Hold Points)'), ('type_b', 'Type B - Combo Package (No Points)')], default='type_c', help_text='Type of booking determines point awarding logic', max_length=20),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='combo_session_number',
            field=models.IntegerField(blank=True, help_text='Which session of the combo? (e.g., 2 of 4)', null=True),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='combo_total_sessions',
            field=models.IntegerField(blank=True, help_text='Total sessions in combo (e.g., 4)', null=True),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Manager who confirmed the arrival', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_arrivals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='is_combo_package',
            field=models.BooleanField(default=False, help_text='Mark if this is a combo package session (no additional points)'),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Upload screenshot of payment/deposit/booking confirmation', null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='points_awarded',
            field=models.BooleanField(default=False, help_text='Have points been awarded to staff?'),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='points_awarded_at',
            field=models.DateTimeField(blank=True, help_text='When points were awarded to staff', null=True),
        ),
        migrations.AddField(
            model_name='taskpackage',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='When customer is scheduled to arrive for service', null=True),
        ),
        migrations.AddIndex(
            model_name='taskpackage',
            index=models.Index(fields=['booking_type', 'arrival_status', 'scheduled_date'], name='task_manage_booking_d7d663_idx'),
        ),
        migrations.AddIndex(
            model_name='taskpackage',
            index=models.Index(fields=['scheduled_date', 'arrival_status'], name='task_manage_schedul_482c63_idx'),
        ),
        migrations.AddIndex(
            model_name='taskpackage',
            index=models.Index(fields=['points_awarded', 'booking_type'], name='task_manage_points__34159d_idx'),
        ),
    ]
