# Generated by Django 4.2.7 on 2026-01-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0008_taskpackage_arrival_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboPackageOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('total_sessions', models.IntegerField(help_text='Total sessions in this combo (e.g., 4 for Cute Combo 4)')),
                ('sessions_used', models.IntegerField(default=0, help_text='How many sessions have been used')),
                ('sessions_remaining', models.IntegerField(help_text='How many sessions are left')),
                ('points_awarded', models.IntegerField(default=0, help_text='Points awarded to staff who sold this combo')),
                ('awarded_at', models.DateTimeField(blank=True, help_text='When points were awarded', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fully_used', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('awarded_to', models.ForeignKey(help_text='Staff who sold this combo package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_sales', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(help_text='Which cat this combo package is for', on_delete=django.db.models.deletion.CASCADE, related_name='combo_packages', to='task_management.cat')),
                ('combo_task_type', models.ForeignKey(help_text='The Combo Front task type (e.g., Cute Combo 4)', on_delete=django.db.models.deletion.PROTECT, related_name='combo_ownerships', to='task_management.tasktype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_combo_packages', to='task_management.customer')),
                ('purchase_package', models.OneToOneField(help_text='The TaskPackage created when combo was sold', on_delete=django.db.models.deletion.CASCADE, related_name='combo_ownership', to='task_management.taskpackage')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='task_manage_custome_b2dcdd_idx'), models.Index(fields=['cat', 'is_active'], name='task_manage_cat_id_91d45b_idx')],
            },
        ),
    ]
