# Generated by Django 4.2.7 on 2026-01-06 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0009_combopackageownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('selected_tasks_json', models.TextField(help_text='JSON array of task IDs')),
                ('total_points', models.IntegerField(default=0)),
                ('scheduled_date', models.DateField(help_text='The appointment date - booking expires day after if no payment')),
                ('scheduled_time', models.TimeField(default='09:00')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed & Converted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_proof', models.ImageField(blank=True, help_text='Payment proof uploaded when customer arrives', null=True, upload_to='pending_booking_proofs/%Y/%m/')),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='task_management.cat')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pending_bookings', to=settings.AUTH_USER_MODEL)),
                ('converted_to_package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_pending_booking', to='task_management.taskpackage')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='task_management.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_date'], name='task_manage_status_a5263f_idx'), models.Index(fields=['customer', 'status'], name='task_manage_custome_7a7598_idx'), models.Index(fields=['created_by', 'status'], name='task_manage_created_c729c1_idx')],
            },
        ),
    ]
