# Generated by Django 4.2.7 on 2025-12-10 12:09

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('reason', models.CharField(choices=[('low_performance', 'Low Performance (Below 850 points)'), ('absence', 'Unauthorized Absence'), ('conduct', 'Misconduct'), ('quality', 'Quality Issues')], max_length=50)),
                ('points_achieved', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('description', models.TextField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='PointsProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('daily_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('projected_monthly_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('projected_end_date_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('days_remaining', models.IntegerField(default=0)),
                ('points_needed_for_target', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('daily_points_required', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_track', models.BooleanField(default=False)),
                ('will_reach_warning', models.BooleanField(default=False)),
                ('will_exceed_target', models.BooleanField(default=False)),
                ('suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('incentive_earned', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('milestone_reached', models.IntegerField(blank=True, null=True)),
                ('is_below_warning_threshold', models.BooleanField(default=False)),
                ('warning_issued', models.BooleanField(default=False)),
                ('warning_issued_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_incentives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Monthly incentives',
                'ordering': ['-month'],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('grooming_count', models.IntegerField(default=0)),
                ('cat_service_count', models.IntegerField(default=0)),
                ('booking_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('grooming_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('booking_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily points',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
