# Generated by Django 4.2.7 on 2025-12-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
