# Generated by Django 4.2.7 on 2025-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('damansara_perdana', 'Damansara Perdana'), ('wangsa_maju', 'Wangsa Maju'), ('shah_alam', 'Shah Alam'), ('bangi', 'Bangi'), ('cheng_melaka', 'Cheng, Melaka'), ('johor_bahru', 'Johor Bahru'), ('seremban', 'Seremban 2'), ('seri_kembangan', 'Seri Kembangan'), ('usj21', 'USJ 21'), ('ipoh', 'Ipoh')], default='main', max_length=50),
        ),
    ]
