# Generated by Django 4.2.7 on 2025-12-12 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['-date', 'user'], 'verbose_name': 'Work Schedule', 'verbose_name_plural': 'Work Schedules'},
        ),
        migrations.AddField(
            model_name='workschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning Shift (8 AM - 12 PM)'), ('afternoon', 'Afternoon Shift (1 PM - 5 PM)'), ('full', 'Full Day (8 AM - 5 PM)'), ('evening', 'Evening Shift (5 PM - 9 PM)'), ('off', 'Day Off')], default='full', max_length=20),
        ),
    ]
