# Generated by Django 4.2.7 on 2025-12-22 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_alter_workschedule_options_workschedule_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('medical', 'Medical Leave'), ('emergency', 'Emergency Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField(help_text='Leave start date')),
                ('end_date', models.DateField(help_text='Leave end date')),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('medical_proof', models.FileField(blank=True, help_text='Medical certificate (required for medical leave)', null=True, upload_to='leave_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending_manager', 'Pending Manager Approval'), ('manager_approved', 'Manager Approved - Pending Admin'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_manager', max_length=30)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, help_text='Admin who gave final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_admin_approved', to=settings.AUTH_USER_MODEL)),
                ('manager_approved_by', models.ForeignKey(blank=True, help_text='Manager who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_manager_approved', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(help_text='Staff requesting leave', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Schedule date')),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('full_day', 'Full Day'), ('off', 'OFF/Rest Day')], help_text='Type of shift', max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Shift start time (null for OFF days)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Shift end time (null for OFF days)', null=True)),
                ('branch', models.CharField(help_text='Branch where staff works this shift', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin/Manager who created this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(help_text='Staff member assigned to this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for swap request')),
                ('status', models.CharField(choices=[('pending_counterpart', 'Pending Other Staff Agreement'), ('pending_manager', 'Pending Manager Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_counterpart', max_length=30)),
                ('counterpart_agreed', models.BooleanField(default=False)),
                ('counterpart_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterpart', models.ForeignKey(help_text='Staff to swap with', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL)),
                ('counterpart_schedule', models.ForeignKey(help_text="Counterpart's shift to swap", on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_counterpart', to='schedule.schedule')),
                ('manager_approved_by', models.ForeignKey(blank=True, help_text='Manager who approved the swap', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='Staff requesting the swap', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('requester_schedule', models.ForeignKey(help_text="Requester's shift to swap", on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_requester', to='schedule.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['requester', 'status'], name='schedule_sh_request_e0980c_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['counterpart', 'status'], name='schedule_sh_counter_058c43_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['status', '-created_at'], name='schedule_sh_status_0f1902_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'staff'], name='schedule_sc_date_9fa431_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['staff', 'date'], name='schedule_sc_staff_i_8fcbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['branch', 'date'], name='schedule_sc_branch_067ac6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('staff', 'date')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff', 'status'], name='schedule_le_staff_i_822525_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='schedule_le_start_d_325b03_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', '-created_at'], name='schedule_le_status_7eddc7_idx'),
        ),
    ]
